### ISSUE TITLE
Repo transfer?

### ISSUE THREAD

**Issue by krwenholz** [ngrok/ngrok-snap#6]
Hi @khiemdoan thanks again for transferring the snap pacakge. What would you think about transferring this repo as well? If we do that, rather than the current fork, links across the internet will continue working, folks will be able to find the latest source, and we'll be better able to preserve your git history. Would you be amenable to this? The organization we use for public projects is just https://github.com/ngrok

Happy Friday!

**Comment by khiemdoan** [comment]
Hi @krwenholz ,
I agree to transfer this repo to the organization.

Happy weekends!

**Comment by khiemdoan** [comment]
There are some errors when I transfer this repo:
`ngrok already has a repository in the khiemdoan/ngrok-snap network and You don’t have the permission to create public repositories on ngrok`

**Comment by krwenholz** [comment]
Ah I think I may know what's wrong. I'm out for the weekend but will get back to you on Monday! Sorry for the hassle.

**Comment by krwenholz** [comment]
Okay so I deleted the old repository in our org, which is the first part of the error. In order to resolve the permissions part, it looks like the best option is to transfer to me, `krwenholz`, and then I can transfer to `ngrok` where I have create permissions. Sound reasonable?

Thanks for your patience and help!

**Comment by krwenholz** [comment]
It's live! Thank you so much @khiemdoan. Have a most excellent week.
